version: '3.4'

services:
    anaconda:
        image: joseew/music-genre-classification_anaconda
        volumes:
            - ./notebooks:/opt/notebooks
            - ./project:/opt/notebooks/project
            - ./data:/opt/notebooks/data
        ports:
            - 8888:8888
    floydhub:
        image: joseew/music-genre-classification_floydhub
        stdin_open: true
        tty: true
        volumes:
            - ./project:/code/project
            - ./data:/code/data